<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KiriScope.Core\KiriScope.Core.csproj" />
    <ProjectReference Include="..\KiriScope.IO\KiriScope.IO.csproj" />
    <ProjectReference Include="..\KiriScope.Resources\KiriScope.Resources.csproj" />
    <ProjectReference Include="..\KiriScope.Runtime\KiriScope.Runtime.csproj" />
    <ProjectReference Include="..\KiriScope.Xp3\KiriScope.Xp3.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
