<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KiriScope.Core\KiriScope.Core.csproj" />
    <ProjectReference Include="..\KiriScope.IO\KiriScope.IO.csproj" />
    <ProjectReference Include="..\KiriScope.Worker.Protocol\KiriScope.Worker.Protocol.csproj" />
  </ItemGroup>

</Project>
